[build]
  command = "npm run build:production"
  publish = "ibrahim-accounting/client/dist"
  
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
